services:
  flask-app:
    build:
      context: flask-app
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
  nginx: 
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - flask-app